---

frontend_rails_env: development
frontend_rbenv_version: 1.9.3-p547
frontend_unicorn_worker_processes: 2
frontend_use_local_source: false
frontend_branch_or_tag: master
frontend_s3_bucket: changeme
bookshelf_max_pages: 100
