---

- name: Ensure existence of necessary packages
  apt: >
      pkg="{{ item }}" state=present
  with_items:
    - postgresql-common
    - postgresql-client
    - libpq-dev
    - libmagickcore-dev
    - libmagickwand-dev
    - libreadline6
    - libreadline6-dev
    - g++
    - libssl-dev
  when: not skip_configuration | default(false)
  tags:
    - packages

- name: Ensure state of ImageMagick policy.xml file
  copy:
    src: ../../../files/imagemagick_policy.xml
    dest: /etc/ImageMagick/policy.xml
    owner: root
    group: root
    mode: 0644
  notify: restart unicorn

- name: Ensure state of Unicorn init script
  template: >
      src=etc_init.d_unicorn_frontend.j2 dest=/etc/init.d/unicorn_frontend
      owner=root group=root mode=0755
  when: not skip_configuration | default(false)
  tags:
    - web
    - initscripts

- name: Ensure state of Unicorn startup script
  template: >
      src=start_unicorn_frontend.sh.j2 dest=/usr/local/sbin/start_unicorn_frontend.sh
      owner=root group=root mode=0755
  when: not skip_configuration | default(false)
  tags:
    - web
    - scripts
    - initscripts

- name: Ensure that Unicorn init script starts and stops on boot/shutdown
  command: update-rc.d unicorn_frontend defaults
  when: not skip_configuration | default(false)
  tags:
    - web
    - initscripts

- name: Update webserver virtual host for frontend app
  template: >
      src="etc_nginx_sites-available_frontend.j2"
      dest="/etc/nginx/sites-available/frontend"
      owner=root group=root mode=0644
  notify: restart nginx
  when: not skip_configuration | default(false)
  tags:
    - nginx
    - web

- name: Symlink webserver virtual host for frontend app
  file: >
      src="/etc/nginx/sites-available/frontend"
      dest="/etc/nginx/sites-enabled/frontend"
      state=link owner=root group=root
  notify: restart nginx
  when: not skip_configuration | default(false)
  tags:
    - nginx
    - web

- name: Make sure that frontend app logs get rotated
  template: >-
      src=etc_logrotate.d_frontend_rails_logs.j2
      dest=/etc/logrotate.d/frontend_rails_logs
      owner=root group=root mode=0644
  when: not skip_configuration | default(false)
  tags:
    - web
    - logrotate


- include: deploy.yml tags=web
  when: do_deployment
