---

- include_vars: "../vars/{{ level }}.yml"
  when: level is defined
  tags:
    - munin

- name: Make sure that the Tomcat packages are installed
  apt: name={{ item }} state=present
  with_items:
    - tomcat7
    - tomcat7-admin

- name: Ensure state of Tomcat startup options file
  template: >-
    src=etc_default_tomcat7.j2 dest=/etc/default/tomcat7
    mode=0644 owner=root group=root
  notify: restart tomcat

- name: Ensure state of Tomcat access control file
  template: >-
    src=tomcat-users.xml.j2 dest=/etc/tomcat7/tomcat-users.xml
    mode=0640 owner=root group=tomcat7
  notify: restart tomcat

- name: Ensure the state of other Tomcat configuration files
  template: >-
    src="{{ item }}.j2" dest="/etc/tomcat7/{{ item }}"
    mode=0644 owner=root group=tomcat7
  with_items:
    - context.xml
    - logging.properties
    - server.xml
    - web.xml
  notify: restart tomcat

- name: Ensure that Tomcat "catalina" logs are rotated correctly
  template: >-
    src=etc_logrotate.d_tomcat7.j2 dest=/etc/logrotate.d/tomcat7
    mode=0644 owner=root group=root
  tags:
    - logs

- name: Ensure that Tomcat AccessLogValve logs are pruned
  template: >-
    src=etc_cron.d_prune-tomcat-access-logs.j2 dest=/etc/cron.d/prune-tomcat-access-logs
    mode=0644 owner=root group=root
  tags:
    - logs

## Tomcat Munin plugins
#

- name: Make sure Perl XML::Simple module is installed
  apt: pkg=libxml-simple-perl state=present
  tags:
    - munin
    - packages

- name: Ensure state of configuration for Munin Tomcat plugin
  template: >-
      src=etc_munin_plugin_conf_d_zzz-tomcat.j2
      dest=/etc/munin/plugin-conf.d/zzz-tomcat
      owner=root group=root mode=0644
  notify: restart munin-node
  tags:
    - munin

- name: Symlink basic Munin Tomcat plugins
  file: >-
    src="/usr/share/munin/plugins/{{ item }}"
    dest="/etc/munin/plugins/{{ item }}"
    state=link
  with_items:
    - tomcat_access
    - tomcat_jvm
    - tomcat_threads
    - tomcat_volume
  tags:
    - munin