---

tomcat_admin_username: tcadmin
tomcat_admin_password: changeme
tomcat_max_mem_mb: 256
tomcat_init_mem_mb: 256

# logfile ages, in days:
# ... "catalina" logs are rotated by logrotate:
tomcat_catalina_log_age: 7
# ... AccessLogValve logs are governed by directives in server.xml.
# The ".log" logs are pruned by a cron.daily script that comes with
# the Ubuntu tomcat7 package, and the access_log logs have to be
# pruned by our own cron job.  See etc_default_tomcat7.j2 and
# etc_logrotate.d_tomcat7.j2.
tomcat_accesslogvalve_log_age: 7
