---

# Clear this out prior to copying and symlinking below
- file: path=/home/dpla/exhibitions state=absent

- name: Check out exhibitions app from its repository (git)
  git: >-
      repo=https://github.com/dpla/exhibitions.git
      dest=/home/dpla/exhibitions-git
      version={{ exhibitions_branch_or_tag | default("master") }}
      force=true
  sudo_user: dpla
  when: not exhibitions_use_local_source

# Symlink to the build directory, to allow local and git builds to coexist neatly
# 1. For a git deployment ...
- file: src=/home/dpla/exhibitions-git dest=/home/dpla/exhibitions state=link
  when: not exhibitions_use_local_source

- name: Check out exhibitions app from mounted directory
  script: copy_local_app.sh
  when: exhibitions_use_local_source

# Symlink (see above)
# 2. For a local deployment ...
- file: src=/home/dpla/exhibitions-local dest=/home/dpla/exhibitions state=link
  when: exhibitions_use_local_source

- name: Update exhibitions app database configuration file
  template: >
      src=db.ini.j2 dest=/home/dpla/exhibitions/db.ini
      owner=dpla group=webapp mode=0640

- name: Update exhibitions app main configuration file
  template: >
      src=application_config_config.ini.j2
      dest=/home/dpla/exhibitions/application/config/config.ini
      owner=dpla group=webapp mode=0640

- name: Temporarily copy private key
  copy: >
      src={{ github_private_key_path | default("~/.ssh/id_rsa") }}
      dest=/home/dpla/git_private_key
      owner=dpla group=dpla mode=0600

- name: Check out exhibitions assets
  git: >-
       repo=https://github.com/dpla/exhibitions-assets.git
       dest="/home/dpla/exhibitions-assets"
       version=master
       force=true
  sudo_user: dpla

- name: Remove temporary private key file
  file: path=/home/dpla/git_private_key state=absent

- name: Ensure exhibitions document root exists
  file: path=/srv/www/exhibitions state=directory owner=dpla group=dpla mode=0755

- name: Build the exhibitions app
  script: build_exhibitions.sh

- name: Ensure existence and permissions of logs directory
  file: >
      path=/srv/www/exhibitions/application/logs
      state=directory owner="www-data" group="www-data" mode=0775

- name: Ensure existence of log file
  file: >
      path=/srv/www/exhibitions/application/logs/errors.log
      state=touch mode=0664 owner="www-data" group="www-data"

- name: Ensure existence of "files" base directory
  file: >
      path="/srv/www/exhibitions/files" state=directory
      mode=0755 owner=dpla group=dpla

- name: Ensure existence of "files" subdirectories
  file: >
      path="/srv/www/exhibitions/files/{{ item }}"
      state=directory mode=0755 owner="www-data" group="www-data"
  with_items:
    - fullsize
    - original
    - square_thumbnails
    - theme_uploads
    - thumbnails

- name: Clear site proxy cache
  command: find /var/cache/nginx -type f -delete
  delegate_to: "{{ item }}"
  with_items: groups.site_proxies
  when: not skip_site_proxy_cache
