---

jenkins_version: 2.60.1
# Get the sha256 checksum from
# http://mirrors.jenkins.io/war-stable/<VERSION>/jenkins.war.sha256
jenkins_sha256: 34fde424dde0e050738f5ad1e316d54f741c237bd380bd663a07f96147bb1390
# Get the md5 sum by running 'md5' or 'md5sum' on the downloaded file (where
# you the maintainer download it and check it before updating this variable)
# In the future when we upgrade to Ansible 2+ we can just use the SHA256 hash
# above because the 'stat' module will be able to do SHA256.
jenkins_md5: 9e14790b2345bf673abb24224eee4d2c
jenkins_python_version: 2.7.13
jenkins_aws_region: us-east-1
jenkins_aws_key: override_me
jenkins_aws_secret_key: override_me
