---

- include_vars: "../vars/{{ level }}.yml"
  when: level is defined
  tags:
  - database

- name: Add cloudant package list
  template: src=cloudant.list.j2 dest=/etc/apt/sources.list.d/cloudant.list
  tags:
    - packages
    - database

- name: Update apt package index for bigcouch
  apt: update_cache=yes
  tags:
    - packages
    - database

- name: Install packages
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - bigcouch
  tags:
    - packages
    - database

- name: Update bigcouch local.ini file
  template: src=local.ini.j2 dest=/opt/bigcouch/etc/local.ini
  notify:
    - restart bigcouch
  tags:
   - database

- name: Update bigcouch VM args file
  template: src=vm.args.erb.j2 dest=/opt/bigcouch/etc/vm.args
  notify:
    - restart bigcouch
  tags:
   - database

- meta: flush_handlers

- name: Add nodes to cluster (not contentqa)
  # This is the typical case.  There is a group of BigCouch nodes and you want
  # each node in the inventory file added to the cluster.
  uri: >
      url="http://{{ inventory_hostname }}:5986/nodes/{{ dbnode_id_name }}@{{ item }}"
      method=PUT body="{}" status_code="201,409"
  with_items: groups['dbnodes']
  when: level != "contentqa"
  tags:
    - database

- name: Add nodes to cluster (contentqa)
  # This is a special case for a content QA environment, where there could be
  # multiple QA hosts, but each one only has a single BigCouch node and you don't
  # want them talking to each other, even though there are multiple dbnodes in
  # the inventory.
  uri: >
      url="http://{{ inventory_hostname }}:5986/nodes/{{ dbnode_id_name }}@{{ inventory_hostname }}"
      method=PUT body="{}" status_code="201,409"
  when: level == "contentqa"
  tags:
    - database

- name: Add logrotate task for bigcouch
  copy: src=etc_logrotate_d_bigcouch dest=/etc/logrotate.d/bigcouch owner=root group=root mode=0644
  tags:
    - database
