---

# Postfix mail configuration common to all cloud servers.
# To run standalone, specify
# --extra-vars "level=<development|staging|production|contentqa>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: AWS Postfix
  hosts: all
  sudo: yes
  roles:
    - aws_postfix
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]
