---

# HTTP provisioning and configuration common to all servers that
# run Nginx.
# To run standalone, specify
# --extra-vars "level=<development|staging|production>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Common httpd configuration
  hosts:
    - api
    - frontend
    - site_proxies
  become: yes
  roles:
    - common_web
