---

# Configuration and provisioning common to all servers.
# To run standalone, specify
# --extra-vars "level=<development|staging|production|contentqa>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Common
  hosts: all
  sudo: yes
  roles:
    - common
