---

# This gets included by ../contentqa_all.yml.

- include: postgresql.yml

# Note that contentqa does not have MySQL.

- include: memcached.yml

- name: Common httpd configuration
  hosts: webapps
  sudo: yes
  roles:
    - common_web
  vars:
    level: contentqa
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]

- include: api.yml
