---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy Exhibitions (staging)
  hosts: exhibitions
  sudo: yes
  serial: 1
  tasks:
    - include: ../roles/omeka/tasks/deploy.yml
  handlers:
    - include: ../roles/omeka/handlers/main.yml
  vars:
    level: staging
  vars_files:
    - "../roles/omeka/defaults/main.yml"
    - "../vars/staging.yml"
    - "../roles/omeka/vars/staging.yml"
