---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy Exhibitions (development)
  hosts: exhibitions
  sudo: yes
  serial: 1
  tasks:
    - include: ../roles/omeka/tasks/deploy.yml
  handlers:
    - include: ../roles/omeka/handlers/main.yml
  vars:
    level: development
  vars_files:
    - "../vars/development.yml"
    - "../roles/omeka/defaults/main.yml"
