---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy frontend (production)
  hosts: frontend
  sudo: yes
  serial: 1
  tasks:
    - include: ../roles/frontend/tasks/deploy.yml
  handlers:
    - include: ../roles/frontend/handlers/main.yml
  vars:
    level: production  
  vars_files:
    - "../vars/production.yml"
    - "../roles/frontend/defaults/main.yml"
    - "../roles/frontend/vars/production.yml"
