---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy API (production  )
  hosts: api
  sudo: yes
  tasks:
    - include: ../roles/api/tasks/deploy.yml
  handlers:
    - include: ../roles/api/handlers/main.yml
  vars:
    level: production  
  vars_files:
    - "../vars/production.yml"
    - "../roles/api/defaults/main.yml"
    - "../roles/api/vars/production.yml"
