---

- include: postgresql.yml level=development

- include: memcached.yml level=development

- name: Common httpd configuration
  hosts: webapps
  become: yes
  roles:
    - common_web
  vars:
    level: development

- name: Common PHP configuration
  hosts: webapps
  become: yes
  roles:
    - common_php
  vars:
    level: development

- name: Webapps
  hosts: webapps
  become: yes
  roles:
    - site_proxy
    - pss
  vars:
    level: development
    do_deployment: true
    skip_configuration: false

- name: Frontend (portal) site
  hosts: webapps
  become: yes
  roles:
    - frontend
    - { role: thumbp, tags: ['thumbp']}
  vars:
    level: development
    do_deployment: true
    skip_configuration: false

- include: api.yml level=development
