---

- include: postgresql.yml

- include: mysql.yml

- include: memcached.yml

- name: Common httpd configuration
  hosts: webapps
  sudo: yes
  roles:
    - common_web
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]

- name: Common PHP configuration
  hosts: webapps
  sudo: yes
  roles:
    - common_php
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]

- name: Content-management and exhibitions services
  hosts: webapps
  sudo: yes
  roles:
    - common_sitenode
    - site_proxy
    - omeka
    - wordpress
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]

- name: Frontend (portal) site
  hosts: webapps
  sudo: yes
  roles:
    - frontend
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]

- include: api.yml
