---

# To run standalone, specify
# --extra-vars "level=<development|staging|production>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- hosts: elasticsearch[0]
  become: false
  tasks:
    - name: Turn off shard replica allocation
      when: initial_run is not defined
      local_action: >
          script ../files/set-allocation.sh off "{{ es_cluster_loadbal }}"

- name: Elasticsearch setup
  hosts: elasticsearch
  serial: 1
  become: yes
  roles:
    - elasticsearch
  pre_tasks:
    - name: Gather ec2 facts
      ec2_facts:
      when: level == 'production' or level == 'staging'
    - name: De-register instance from loadbalancer
      local_action: ec2_elb
      when: level == 'production' or level == 'staging'
      become: false
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ es_elb_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        state: absent
    - name: Wait for connections to drain
      when: level == 'production' or level == 'staging'
      wait_for: >-
          host="{{ inventory_hostname }}" port="9200" state=drained timeout=60
      ignore_errors: yes
  post_tasks:
    - name: Wait for ES node to come back up
      become: false
      # Assume default port, 9200.
      local_action: >
          wait_for host="{{ inventory_hostname }}" port=9200 delay=30 timeout=300
    - name: Register instance with loadbalancer again
      local_action: ec2_elb
      when: level == 'production' or level == 'staging'
      become: false
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ es_elb_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        state: present
        wait_timeout: 22

- hosts: elasticsearch[0]
  become: false
  tasks:
    - name: Turn shard replica allocation back on
      local_action: >
          script ../files/set-allocation.sh on "{{ es_cluster_loadbal }}"
