---

# To run standalone, specify
# --extra-vars "level=<development|staging|production>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Ingestion App
  hosts:
    - ingestion_app
    - worker
  sudo: yes
  roles:
    - ingestion_app
  vars:
    skip_configuration: false
    do_deployment: true
