---

# To run standalone, specify
# --extra-vars "level=<development|staging|production>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Ingestion App
  hosts:
    - ingestion_app
    - worker
  sudo: yes
  roles:
    - { role: ingestion_app, tags: ['ingestion_app']}
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]
