---

# Reboot staging or production
# Do not run this directly; use reboot_staging.yml or reboot_production.yml!

- name: Instances that can be rebooted in parallel
  # TODO:  pre and post tasks that put cms sites and frontend
  # into maintenance mode, perhaps via the siteproxies.
  # (503 Service Unavailable, custom maintenance page)
  # Otherwise, there could be 502 Gateway Error or 500 Server Error
  # responses whent the PostgreSQL database or CMS webserver go
  # offline.
  hosts:
    - ingestion
    - cms
    - geocoder
  become: yes
  tasks:
    - name: Reboot
      command: /sbin/shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to come back up
      become: false
      local_action: >-
          wait_for host="{{ inventory_hostname }}" port="22"
          delay=60 timeout=500

- include: reboot_dbnodes.yml

- include: reboot_elasticsearch.yml

- include: reboot_postgresql.yml

- include: reboot_api.yml

- include: reboot_frontend.yml

- include: reboot_siteproxy.yml
