---

- include: pg_maintenance_on.yml
# TODO:  When Ansible version 2 is stable, add a "where:" condition here so
# so that the playbook is not even included if some condition is False.

- name: Reboot PostgreSQL server
  hosts: postgresql_dbs
  sudo: true
  tasks:
    - name: Reboot
      command: /sbin/shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for it to come back up
      sudo: false
      local_action: >-
        wait_for host="{{ inventory_hostname }}"
        port=5432 delay=40 timeout=600

- include: pg_maintenance_off.yml
# TODO: see above
