---

- include: clean.yml
  when: clean_thumbp | default(false)

- name: Ensure existence of the "thumbp" account
  user:
    name: thumbp
    comment: "thumbp privsep user"
    home: /opt/thumbp
    shell: /bin/bash
    state: present
  tags:
    - users

- name: Ensure state of log directory
  file: path=/var/log/thumbp state=directory owner=thumbp mode=0755

- name: Ensure state of opt directory
  file: path=/opt/thumbp state=directory owner=thumbp mode=0755

- name: Ensure state of installation directory
  file: path=/opt/thumbp/thumbp state=directory owner=thumbp mode=0755

- name: Ensure state of src directory
  file: path=/opt/thumbp/src state=directory owner=thumbp mode=0755

- name: Ensure state of src subdirectories
  file:
    path: "/opt/thumbp/src/{{ item }}"
    state: directory
    owner: thumbp
    mode: 0755
  with_items:
    - thumbp-local
    - thumbp-git

- name: Make sure that NVM is installed
  become_user: thumbp
  script: "../../../files/install_nvm.sh {{ thumbp_nvm_version }}"
  register: script_result
  changed_when: "'Success: changed' in script_result.stdout"
  notify: restart thumbp

- include: deploy.yml
  when: do_deployment

- name: Ensure state of init script
  template: >-
    src=etc_init.d_thumbp.j2 dest=/etc/init.d/thumbp
    owner=root group=root mode=0755
  notify: restart thumbp

- name: Clear init script runlevels in case of a change
  command: update-rc.d -f thumbp remove

- name: Ensure init script run levels
  command: update-rc.d thumbp defaults

- name: Ensure state of logrotate configuration
  copy:
    src: etc_logrotate.d_thumbp
    dest: /etc/logrotate.d/thumbp
    owner: root
    group: root
    mode: 0644
