---

exhibitions_use_local_source: false
exhibitions_branch_or_tag: "master"
exhibitions_api_key: "{{ api_key }}"

# PHP-FPM tuning parameters
omeka_php_max_children: 10
omeka_php_start_servers: 2
omeka_php_min_spare_servers: 2
omeka_php_max_spare_servers: 4
omeka_php_max_requests: 500

skip_site_proxy_cache: false
