---

api_unicorn_worker_processes: 2
api_use_local_source: false
api_branch_or_tag: master
api_rails_env: development
api_rbenv_version: 1.9.3-p547
qa_app_username: qa
# password is "changeme"
qa_app_md5_password: "$apr1$bTHb7fKA$glS0Kk6zI6ny0GW0hPerk/"
