---

# Set up a central server that is used for cron jobs and reports.
# Works independently of staging, production, and contentqa and, therefore,
# needs its own inventory file.

- name: Gather facts for all hosts
  # The inventory file has other hosts that have their stats collected, but that
  # are not configured by any of the tasks in this playbook.
  hosts: all

- name: Common
  hosts: central
  sudo: yes
  roles:
    - common
  vars:
    internal_network_interface: ansible_eth0

