---

- name: Common
  hosts: all
  sudo: yes
  roles:
    - common
  vars:
    level: development
  vars_files:
    - [ "vars/development.yml", "vars/defaults.yml" ]

- include: playbooks/dev_loadbalancer.yml

- include: playbooks/dbnodes.yml level=development

- include: playbooks/elasticsearch.yml level=development

- include: playbooks/dev_webapps.yml level=development
