---

# Configuration for all staging hosts.

# For first-time initialization:
#   - run this with --extra-vars "initial_run=true"
#     to prevent an error with Elasticsearch shard replication.
#   - See the comment in playbooks/siteproxy.yml regarding
#     the loadbalancer health check.

- include: playbooks/common.yml level=staging

- include: playbooks/aws_postfix.yml level=staging

- include: playbooks/dbnodes.yml level=staging

- include: playbooks/elasticsearch.yml level=staging

- include: playbooks/postgresql.yml level=staging

- include: playbooks/mysql.yml level=staging

- include: playbooks/memcached.yml level=staging

- include: playbooks/common_httpd.yml level=staging

# The siteproxy playbook should come before the other web-related ones to ensure that
# the site proxy cache exists before the other ones try to clear it.
- include: playbooks/siteproxy.yml level=staging

- name: Content management systems
  hosts:
    - cms-stg
  sudo: yes
  roles:
    - common_php
    - common_sitenode
    - omeka
    - wordpress
  vars:
    level: staging
  vars_files:
    - ["vars/staging.yml", "vars/defaults.yml"]

- name: Frontend (portal) site
  hosts: frontend
  sudo: yes
  roles:
    - frontend
  vars:
    level: staging
  vars_files:
    - ["vars/staging.yml", "vars/defaults.yml"]

- include: playbooks/api.yml level=staging

- include: playbooks/ingestion.yml
