---

- name: Ensure existence of necessary packages
  apt: >
      pkg="{{ item }}" state=present
  with_items:
    - postgresql-common
    - libpq-dev
    - libsqlite3-dev
    - g++
    - libreadline6
    - libreadline6-dev
    - zip
  when: not skip_configuration
  tags:
    - packages

- name: Ensure state of Unicorn init script
  template: >
      src=etc_init.d_unicorn_api.j2 dest=/etc/init.d/unicorn_api
      owner=root group=root mode=0755
  when: not skip_configuration
  tags:
    - web
    - initscripts

- name: Ensure state of Unicorn startup script
  template: >
      src=start_unicorn_api.sh.j2 dest=/usr/local/sbin/start_unicorn_api.sh
      owner=root group=root mode=0755
  when: not skip_configuration
  tags:
    - web

- name: Clear existing unicorn init script run levels in case of change
  command: update-rc.d -f unicorn_api remove
  when: not skip_configuration
  tags:
    - web
    - initscripts

- name: Ensure Unicorn init script run levels
  command: update-rc.d unicorn_api defaults 21 18
  when: not skip_configuration
  tags:
    - web
    - initscripts

##
# Clean up delayed_job init scripts and processes that used to be created in
# earlier versions of this file
- name: Stop obsolete delayed_job if it exists and is running
  service: name=delayed_job_api state=stopped
  ignore_errors: yes
  tags:
    - web
    - initscripts

- name: Clear obsolete delayed_job init script run levels if they are set
  command: update-rc.d -f delayed_job_api remove
  tags:
    - web
    - initscripts

- name: Ensure that obsolete delayed_job control script is absent
  file: path=/usr/local/sbin/delayed_job_api.sh state=absent
  tags:
    - web
    - initscripts

- name: Ensure that obsolete QA app htpasswd file is absent
  file: path=/etc/nginx/qa_htpasswd state=absent
  notify: restart nginx
  when: not skip_configuration
  tags:
    - nginx
    - web
    - htpasswd

### end cleanup

- name: Update webserver virtual host for api app
  template: >
      src="etc_nginx_sites-available_api.j2"
      dest="/etc/nginx/sites-available/api"
      owner=root group=root mode=0644
  notify: restart nginx
  when: not skip_configuration
  tags:
    - nginx
    - web

- name: Symlink webserver virtual host for api app
  file: >
      src="/etc/nginx/sites-available/api"
      dest="/etc/nginx/sites-enabled/api"
      state=link owner=root group=root
  notify: restart nginx
  when: not skip_configuration
  tags:
    - nginx
    - web

- name: Make sure that API app logs get rotated
  template: >-
      src=etc_logrotate.d_api_rails_logs.j2
      dest=/etc/logrotate.d/api_rails_logs
      owner=root group=root mode=0644
  when: not skip_configuration
  tags:
    - logrotate

- include: deploy.yml tags=web
  when: do_deployment
