---

- include_vars: "../vars/{{ level }}.yml"
  when: level is defined
  tags:
    - api
    - web
    - nginx

- name: Ensure existence of necessary packages
  apt: >
      pkg="{{ item }}" state=present
  with_items:
    - postgresql-common
    - libpq-dev
    - libsqlite3-dev
    - g++
  tags:
    - packages
    - api

- name: Ensure state of Unicorn init script
  template: >
      src=etc_init.d_unicorn_api.j2 dest=/etc/init.d/unicorn_api
      owner=root group=root mode=0755
  tags:
    - api
    - web

- name: Ensure state of Unicorn startup script
  template: >
      src=start_unicorn_api.sh.j2 dest=/usr/local/sbin/start_unicorn_api.sh
      owner=root group=root mode=0755
  tags:
    - api
    - web

- name: Clear existing unicorn init script run levels in case of change
  command: update-rc.d -f unicorn_api remove
  tags:
    - api
    - web

- name: Ensure Unicorn init script run levels
  command: update-rc.d unicorn_api defaults 21 18
  tags:
    - api
    - web

- name: Ensure state of delayed job init script
  template: >
      src=etc_init.d_delayed_job_api.j2 dest=/etc/init.d/delayed_job_api
      owner=root group=root mode=0755
  tags:
    - api
    - web

- name: Ensure state of delayed job control script
  template: >
      src=delayed_job_api.sh.j2 dest=/usr/local/sbin/delayed_job_api.sh
      owner=root group=root mode=0755
  tags:
    - api
    - web

- name: Clear existing unicorn init script run levels in case of change
  command: update-rc.d -f delayed_job_api remove
  tags:
    - api
    - web

- name: Ensure delayed job init script run levels
  command: update-rc.d delayed_job_api defaults 20 19
  tags:
    - api
    - web

- name: Update webserver virtual host for api app
  template: >
      src="etc_nginx_sites-available_api.j2"
      dest="/etc/nginx/sites-available/api"
      owner=root group=root mode=0644
  notify: restart nginx
  tags:
    - api
    - nginx
    - web

- name: Symlink webserver virtual host for api app
  file: >
      src="/etc/nginx/sites-available/api"
      dest="/etc/nginx/sites-enabled/api"
      state=link owner=root group=root
  notify: restart nginx
  tags:
    - api
    - nginx
    - web

- name: Ensure state of QA app's password file
  template: >
      src="qa_htpasswd.j2"
      dest="/etc/nginx/qa_htpasswd"
      owner=root group=www-data mode=0640
  notify: restart nginx
  tags:
    - api
    - nginx
    - web
    - htpasswd

- include: deploy.yml
