---

- name: Ensure existence of necessary packages
  apt: >
      pkg="{{ item }}" state=present
  with_items:
    - postgresql-common
    - libpq-dev
    - libsqlite3-dev
    - g++
    - libreadline6
    - libreadline6-dev
    - zip
  when: not skip_configuration | default(false)
  tags:
    - packages


## Init scripts and control scripts
#

- name: Ensure state of Unicorn init script
  template: >
      src=etc_init.d_unicorn_api.j2 dest=/etc/init.d/unicorn_api
      owner=root group=root mode=0755
  when: not skip_configuration | default(false)
  tags:
    - web
    - initscripts

- name: Ensure state of Unicorn startup script
  template: >
      src=start_unicorn_api.sh.j2 dest=/usr/local/sbin/start_unicorn_api.sh
      owner=root group=root mode=0755
  when: not skip_configuration | default(false)
  tags:
    - web

- name: Clear existing unicorn init script run levels in case of change
  command: update-rc.d -f unicorn_api remove
  when: not skip_configuration | default(false)
  tags:
    - web
    - initscripts

- name: Ensure Unicorn init script run levels
  command: update-rc.d unicorn_api defaults 21 18
  when: not skip_configuration | default(false)
  tags:
    - web
    - initscripts

- name: Ensure state of delayed job init script
  when: api_enable_contentqa
  template:
    src: etc_init.d_delayed_job_api.j2
    dest: /etc/init.d/delayed_job_api
    owner: root
    group: root
    mode: 0755
  notify: restart delayed_job
  tags:
    - web
    - initscripts

- name: Ensure state of delayed job control script
  when: api_enable_contentqa
  template:
    src: delayed_job_api.sh.j2
    dest: /usr/local/sbin/delayed_job_api.sh
    owner: root
    group: root
    mode: 0755
  notify: restart delayed_job
  tags:
    - web
    - initscripts

- name: Stop legacy delayed_job if it is running after an upgrade and unwanted
  when: not api_enable_contentqa
  shell: pkill -9 -f delayed_job
  register: pkill_result
  # The `shell' module returns -9 if the process not running, and it is OK if it
  # was not.
  failed_when: "pkill_result.rc != 0 and pkill_result.rc != -9"
  changed_when: pkill_result.rc == 0
  tags:
    - web
    - initscripts

- name: "Clear delayed_job runlevels"
  # In case of a change, or if it's been deselected, all the same
  when: api_enable_contentqa
  command: update-rc.d -f delayed_job_api remove
  tags:
    - web
    - initscripts

- name: Set delayed_job runlevels if contentqa is selected
  when: api_enable_contentqa
  command: update-rc.d delayed_job_api defaults
  tags:
    - web
    - initscripts

- name: Clear legacy delayed_job init script if contentqa is deselected
  when: not api_enable_contentqa
  file: path=/etc/init.d/delayed_job_api state=absent
  tags:
    - web
    - initscripts

- name: Clear legacy delayed_job control script if contentqa is deselected
  when: not api_enable_contentqa
  file: path=/usr/local/sbin/delayed_job_api.sh state=absent
  tags:
    - web
    - initscripts

## End of init scripts / control scripts section


- name: Ensure that legacy QA app htpasswd file is absent
  when: not api_enable_contentqa and not skip_configuration
  file: path=/etc/nginx/qa_htpasswd state=absent
  notify: restart nginx
  tags:
    - nginx
    - web
    - htpasswd

- name: Ensure state of QA app's password file
  when: api_enable_contentqa and not skip_configuration
  template:
      src: qa_htpasswd.j2
      dest: /etc/nginx/qa_htpasswd
      owner: root
      group: www-data
      mode: 0640
  notify: restart nginx
  tags:
    - nginx
    - web
    - htpasswd

- name: Update webserver virtual host for api app
  template: >
      src="etc_nginx_sites-available_api.j2"
      dest="/etc/nginx/sites-available/api"
      owner=root group=root mode=0644
  notify: restart nginx
  when: not skip_configuration | default(false)
  tags:
    - nginx
    - web

- name: Symlink webserver virtual host for api app
  file: >
      src="/etc/nginx/sites-available/api"
      dest="/etc/nginx/sites-enabled/api"
      state=link owner=root group=root
  notify: restart nginx
  when: not skip_configuration | default(false)
  tags:
    - nginx
    - web

- name: Make sure that API app logs get rotated
  template: >-
      src=etc_logrotate.d_api_rails_logs.j2
      dest=/etc/logrotate.d/api_rails_logs
      owner=root group=root mode=0644
  when: not skip_configuration | default(false)
  tags:
    - logrotate

- include: deploy.yml tags=web
  when: do_deployment
